management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      default-zone: http://192.168.72.165:8761/eureka
  instance:
    hostname: 192.168.72.165
    preferIpAddress: 'true'
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
spring:
  cloud:
    inetutils:
      preferredNetworks: 192.168.72.165
  application:
    name: order-service
server:
  port: '1234'
